version: "3.6"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    restart: on-failure
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
